### ISSUE TITLE
RuntimeError: Index put requires the source and destination dtypes match, got Int for the destination and Long for the source.

### ISSUE THREAD

**Issue by Pavankunchala** [yumingj/Text2Human#1]
I have been trying to get the python ui_demo.py running

when I am trying to generate the image, after loading the pose and generating the shape

I get it no matter what kind of prompt i am giving i even tried to give the ones that are same in the demo

I am getting this error

RuntimeError: Index put requires the source and destination dtypes match, got Int for the destination and Long for the source.

**Comment by yumingj** [comment]
Hi, thanks for your interest in our work!

May I know which PyTorch version you use? Have you installed the environment by strictly following the ReadMe?  We don't have a problem with the UI demo from our side. 

Thanks!

**Comment by Pavankunchala** [comment]
1.11.0

**Comment by yumingj** [comment]
Could you please kindly show me which line of the code causes the error so that it would be easy for me to track the error? Thanks!

**Comment by etomasic** [comment]
I also got this error when using pytorch 1.7.1. I fixed it by putting "int(...)" around the right sides of the code in lines 458, 462 and 466 of models/sample_model.py. (The error only appeared for line 458, but I figured I should put it around the other lines given their similarity.)
