### ISSUE TITLE
can you provide the details of dataset preparation?

### ISSUE THREAD

**Issue by gouchaonijiao** [yumingj/Text2Human#16]
Can you provide the details of dataset preparation? Since I can not understand the meaning of the 15 attributes in "shape ann file". Thanks!

**Comment by yumingj** [comment]
Hi The definition of the the attributes are defined here: https://github.com/yumingj/Text2Human/blob/b4ffaf6cd82b195f258c8608455374147c188f99/utils/language_utils.py#L85

They are a little bit different from the original dataset annotations.

**Comment by gouchaonijiao** [comment]
thanks for your reply and your excellent work too!!

**Comment by gouchaonijiao** [comment]
> Hi The definition of the the attributes are defined here:
> 
> https://github.com/yumingj/Text2Human/blob/b4ffaf6cd82b195f258c8608455374147c188f99/utils/language_utils.py#L85
> 
> They are a little bit different from the original dataset annotations.

hello! I have some quetions about the following code
"    for text_id, text in enumerate(parsed_texts):
        user_embeddings = model.encode(text)
        if ('man' in text) and (text_id == 0):
            human_attr[0] = 0
            human_attr[1] = 0

        if ('woman' in text or 'lady' in text) and (text_id == 0):
            human_attr[0] = 1
            human_attr[1] = 2"

according to the code,why there are some human_attr's value are [0,3], like MEN-Denim-id_00005447-01_4_full.png 0 3 3 3 0 2 4 3 0 1 1 0 0 1 0

**Comment by yumingj** [comment]
I enforce the attributes value using the if-clause for the better inference results, as it is hard to generate man with long hair due to the dataset bias.

**Comment by gouchaonijiao** [comment]
Thanks a lot for your explanation!
