### ISSUE TITLE
about the processed dataset

### ISSUE THREAD

**Issue by gouchaonijiao** [yumingj/Text2Human#17]
Hi! I am sorry to bother you again. The processed dataset you made interests me a lot and I want to know how you fused the clothing color and clothing fabric annotations into one texture annotation. For the reason that I can not find the details in "language_utils.py" ,
def generate_texture_attributes(user_text):
    parsed_texts = user_text.split(',')

    attr = []
    for text in parsed_texts:
        if ('pure color' in text) or ('solid color' in text):
            attr.append(4)
        elif ('spline' in text) or ('stripe' in text):
            attr.append(3)
        elif ('plaid' in text) or ('lattice' in text):
            attr.append(5)
        elif 'floral' in text:
            attr.append(1)
        elif 'denim' in text:
            attr.append(0)
        else:
            attr.append(17)

    if len(attr) == 1:
        attr.append(attr[0])
        attr.append(17)

    if len(attr) == 2:
        attr.append(17)

    return attr

**Comment by yumingj** [comment]
Hi, please refer to https://github.com/yumingj/Text2Human/issues/4
