### ISSUE TITLE
how you fused the clothing color and clothing fabric annotations into one texture annotation

### ISSUE THREAD

**Issue by gouchaonijiao** [yumingj/Text2Human#18]
Hi,your work is very outstanding and the datasets you make also is so helpful for me . But I don't know that compare with the raw annotations ,what do the 18 codebooks represent respectively? Hope for your reply!

**Comment by yumingj** [comment]
Hi, please refer to the issue https://github.com/yumingj/Text2Human/issues/4

**Comment by gouchaonijiao** [comment]
Thanks for your nice work again!
