### ISSUE TITLE
Google Drive permission error

### ISSUE THREAD

**Issue by rlayne** [yumingj/Text2Human#2]
Cannot download any of the pretrained models, just gives a 403 error.

**Comment by yumingj** [comment]
Thanks for your interest in our work!

This is the link to our pretrained models: https://drive.google.com/file/d/1VyI8_AbPwAUaZJPaPba8zxsFIWumlDen/view?usp=sharing

I just checked that I don't have a problem with downloading these models. Could you please try again? Thanks!
