### ISSUE TITLE
Is it OK to add your pretrained models to Hugging Face Hub?

### ISSUE THREAD

**Issue by hysts** [yumingj/Text2Human#5]
Hi, @yumingj
Thank you for sharing this awesome work.

Is it OK for me to make the provided pretrained models publicly available in Hugging Face Hub?
I made [this demo app](https://huggingface.co/spaces/hysts/Text2Human), but as I wasn't sure if it's OK, the pretrained models are in private repo for now.

**Comment by hysts** [comment]
Well, as you already seems to have an Hugging Face account, I think it's natural and better if you could add them yourself.
How to add models: https://huggingface.co/docs/hub/models-uploading

**Comment by yumingj** [comment]
Thanks @hysts !

I prefer to make the current pretrained models in the private repo for now. I am training a new model on a more diverse and large-scale dataset. I am considering replacing the pretrained models with the newly trained ones if the performance is better.

I prefer to make the newly trained models publicly available when it is ready. Once it is ready, I will also let you know and update the web demo in your hugging face! Thanks!!

**Comment by hysts** [comment]
OK, I understand. Thanks!

**Comment by RylanSchaeffer** [comment]
Commenting to follow! @yumingj , any updates on the new model?

**Comment by yumingj** [comment]
Hi @RylanSchaeffer , I have updated the new model trained on a larger dataset! You can find that in our model zoo.
