### ISSUE TITLE
Unofficial Colab

### ISSUE THREAD

**Issue by neverix** [yumingj/Text2Human#9]
Hi!

This is a very impressive model. I built a [Colab notebook](https://colab.research.google.com/drive/1AVwbqLwMp_Gz3KTCgBTtnGVtXIlCZDPk#scrollTo=wMeHXDu11ebH) for it. Can it be added as an alternative to the upcoming official?

**Comment by yumingj** [comment]
Hi, thanks for your efforts! I have updated the demo link in Readme
